//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class APSMessage;

@protocol AKAppleIDPushHelperServiceDelegate <NSObject>
- (void)processPushMessage:(APSMessage *)arg1;
- (_Bool)shouldSuppressPushMessage:(APSMessage *)arg1;
@end

