//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary;

@interface AKAppleIDUserInformationResponse : NSObject
{
    _Bool _isUnderage;
    _Bool _isLegacyStudent;
    unsigned long long _securityLevel;
}

@property(readonly) _Bool isLegacyStudent; // @synthesize isLegacyStudent=_isLegacyStudent;
@property(readonly) _Bool isUnderage; // @synthesize isUnderage=_isUnderage;
@property(readonly) unsigned long long securityLevel; // @synthesize securityLevel=_securityLevel;
@property(readonly, copy) NSDictionary *dictionaryRepresentation;
- (id)initWithResponseBody:(id)arg1;

@end

