//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AKURLRequestProvider.h"

@class AKAppleIDAuthenticationContext, NSString;

@interface AKFollowUpRequestProvider : NSObject <AKURLRequestProvider>
{
    AKAppleIDAuthenticationContext *_context;
}

- (void).cxx_destruct;
- (id)bodyWithAuthKitBody:(id)arg1;
- (void)signRequest:(id)arg1;
- (id)requestWithBody:(id)arg1 error:(id *)arg2;
- (id)context;
- (id)initWithContext:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

