//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AKFollowUpServiceController.h"

@class NSString;

@interface AKFollowUpServiceControllerImpl : NSObject <AKFollowUpServiceController>
{
    id <AKURLRequestProvider> _requestProvider;
    id <AKFollowUpAuthHandler> _reauthHandler;
}

- (void).cxx_destruct;
- (void)_executeRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)fetchFollowUpDefinitionsWithIdmsData:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)setAuthenticationDelegate:(id)arg1;
- (id)initWithRequestProvider:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

