//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AKAnisetteServiceProtocol.h"

@class AKURLSession;

@interface AKNativeAnisetteService : NSObject <AKAnisetteServiceProtocol>
{
    AKURLSession *_URLSession;
}

+ (unsigned long long)activeAnisetteDSID;
+ (void)initialize;
- (void).cxx_destruct;
- (id)_createSyncURLRequestWithMID:(id)arg1 SRM:(id)arg2 routingInfo:(unsigned long long)arg3;
- (id)_createProvisioningEndURLRequestWithCPIM:(id)arg1;
- (id)_createProvisioningStartURLRequest;
- (void)eraseAnisetteWithCompletion:(CDUnknownBlockType)arg1;
- (void)syncAnisetteWithSIMData:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_unsafe_provisionAnisetteWithCompletion:(CDUnknownBlockType)arg1;
- (void)provisionAnisetteWithCompletion:(CDUnknownBlockType)arg1;
- (id)_unsafe_anisetteDataForDSID:(unsigned long long)arg1 withError:(id *)arg2;
- (id)_unsafe_anisetteDataWithRoutingInfoForDSID:(unsigned long long)arg1 withError:(id *)arg2;
- (void)legacyAnisetteDataForDSID:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)fetchAnisetteDataAndProvisionIfNecessary:(_Bool)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (id)init;

@end

