//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AKSRPOperation : NSObject
{
}

+ (_Bool)performWithURL:(id)arg1 SRPContext:(id)arg2 error:(struct __CFError **)arg3;

@end

