//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AKAppleIDAuthenticationContext, NSDictionary, NSMutableURLRequest, NSURLRequest;

@protocol AKURLRequestProvider <NSObject>
- (NSDictionary *)bodyWithAuthKitBody:(NSDictionary *)arg1;
- (void)signRequest:(NSMutableURLRequest *)arg1;
- (NSURLRequest *)requestWithBody:(NSDictionary *)arg1 error:(id *)arg2;
- (AKAppleIDAuthenticationContext *)context;
- (id)initWithContext:(AKAppleIDAuthenticationContext *)arg1;
@end

